export const BJJ_TAG_REFERENCE: Record<string, string> = {
  // Guard
  HG: "Half Guard",
  DHG: "Deep Half Guard",
  DLR: "De La Riva",
  RDLR: "Reverse De La Riva",
  SLX: "Single Leg X",
  XG: "X-Guard",
  ButtG: "Butterfly Guard",
  ClosG: "Closed Guard",
  OpenG: "Open Guard",
  SpidG: "Spider Guard",
  LassG: "Lasso Guard",
  SitG: "Sit-up Guard",
  Lapel: "Lapel Guard",
  WormG: "Worm Guard",
  RWormG: "Reverse Worm Guard",
  SquidG: "Squid Guard",
  OctG: "Octopus Guard",
  RubG: "Rubber Guard",
  CrabR: "Crab Ride",
  TruckG: "Truck Guard",
  KShield: "Knee Shield / Z-Guard",
  ZG: "Z-Guard",
  WaitG: "Waiter Guard",

  // Submission
  RNC: "Rear Naked Choke",
  AnaC: "Anaconda Choke",
  Darce: "Darce Choke",
  Guill: "Guillotine",
  IHH: "Inside Heel Hook",
  OHH: "Outside Heel Hook",
  EstLk: "Estima Lock",
  ToeLk: "Toe Lock",
  KneeB: "Kneebar",
  FootLk: "Footlock",
  SFL: "Straight Footlock",
  Omo: "Omoplata",
  Tri: "Triangle",
  Gogo: "Gogoplata",
  BicepS: "Bicep Slicer",
  CanOp: "Can Opener",
  ArmB: "Armbar",
  Kimura: "Kimura",
  Ameri: "Americana",
  WristLk: "Wrist Lock",

  // Position / Top
  Mount: "Mount",
  SMt: "S-Mount",
  SideB: "Side Back",
  BackT: "Back Take",
  BackMt: "Back Mount",
  KoB: "Knee on Belly",
  NS: "North-South",
  Scarf: "Scarf Hold",
  Turtle: "Turtle",
  "50/50": "50/50 Guard",
  Ashi: "Ashi Garami",
  SLAshi: "Single Leg Ashi Garami",
  Saddle: "Honey Hole / Saddle",
  OutAshi: "Outside Ashi",

  // Takedown & Entry
  TD: "Takedown",
  SingL: "Single Leg",
  DoubL: "Double Leg",
  BodyLk: "Body Lock",
  JudoTH: "Judo Throw",
  InTrip: "Inside Trip",
  Throw: "Throw",
  GPull: "Guard Pull",
  KnElb: "Knee Elbow",

  // Sweep & Pass
  Bolo: "Berimbolo",
  TorrP: "Torreando Pass",
  StackP: "Stack Pass",
  SmashP: "Smash Pass",
  LegPP: "Leg Pummeling Pass",
  KCP: "Knee Cut Pass",
  HalfP: "Half Pass",
  LongSP: "Long Step Pass",
  BullP: "Bullfight Pass",
  SingSw: "Single Take Sweep",
  HipSw: "Hip Sweep",
  ScsSw: "Scissor Sweep",

  // Misc
  Gi: "Gi",
  NoGi: "No-Gi",
  LegLk: "Leg Lock",
  HQ: "Headquarters",
}

export function buildTagReferencePrompt(): string {
  const lines = Object.entries(BJJ_TAG_REFERENCE).map(([abbr, full]) => `${abbr} = ${full}`)
  return lines.join("\n")
}
