import type { RadarSourceConfig } from "@/lib/types/radar"

export const RADAR_SOURCES: RadarSourceConfig[] = [
  {
    id: "tldr-ai",
    label: "TLDR AI",
    tier: "tier1-daily",
    cadence: "6h",
    intervalHours: 6,
    mode: "rss",
    endpoint: "https://tldr.tech/api/rss/ai",
    active: true,
  },
  {
    id: "the-rundown-ai",
    label: "The Rundown AI",
    tier: "tier1-daily",
    cadence: "24h",
    intervalHours: 24,
    mode: "rss",
    endpoint: "https://www.therundown.ai/rss",
    active: true,
  },
  {
    id: "x-akhaliq",
    label: "@_akhaliq (manual)",
    tier: "tier1-daily",
    cadence: "6h",
    intervalHours: 6,
    mode: "manual",
    endpoint: "https://x.com/_akhaliq",
    active: false,
  },
  {
    id: "the-batch",
    label: "The Batch",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "html",
    endpoint: "https://www.deeplearning.ai/the-batch/",
    active: true,
  },
  {
    id: "import-ai",
    label: "Import AI",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://importai.substack.com/feed",
    active: true,
  },
  {
    id: "latent-space",
    label: "Latent Space",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://www.latent.space/feed",
    active: true,
  },
  {
    id: "raschka",
    label: "Sebastian Raschka",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://magazine.sebastianraschka.com/feed",
    active: true,
  },
  {
    id: "arxiv",
    label: "arXiv AI/ML",
    tier: "tier3-research",
    cadence: "24h",
    intervalHours: 24,
    mode: "rss",
    endpoint: "https://rss.arxiv.org/rss/cs.AI+cs.LG",
    active: true,
  },
  {
    id: "hf-daily-papers",
    label: "Hugging Face Daily Papers",
    tier: "tier3-research",
    cadence: "6h",
    intervalHours: 6,
    mode: "api",
    endpoint: "https://huggingface.co/api/daily_papers",
    active: true,
  },
  {
    id: "nature-digital-medicine",
    label: "Nature Digital Medicine",
    tier: "medical-ai",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://www.nature.com/npjdigitalmed.rss",
    active: true,
  },
  {
    id: "radiology-ai",
    label: "Radiology AI",
    tier: "medical-ai",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://pubs.rsna.org/action/showFeed?type=etoc&feed=rss&jc=ai",
    active: true,
  },
  {
    id: "msr-health",
    label: "Microsoft Research Health",
    tier: "medical-ai",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://www.microsoft.com/en-us/research/blog/feed/",
    active: true,
  },
  {
    id: "moduletter",
    label: "모두레터",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 12,
    mode: "html",
    endpoint: "https://moduletter.stibee.com",
    active: true,
  },
]

export function getSourceConfig(sourceId: RadarSourceConfig["id"]): RadarSourceConfig | undefined {
  return RADAR_SOURCES.find((source) => source.id === sourceId)
}
