import type { RadarSourceConfig } from "@/lib/types/radar"

export const RADAR_SOURCES: RadarSourceConfig[] = [
  {
    id: "tldr-ai",
    label: "TLDR AI",
    tier: "tier1-daily",
    cadence: "6h",
    intervalHours: 6,
    mode: "rss",
    endpoint: "https://tldr.tech/api/rss/ai",
    active: true,
  },
  {
    id: "the-rundown-ai",
    label: "The Rundown AI",
    tier: "tier1-daily",
    cadence: "24h",
    intervalHours: 24,
    mode: "rss",
    endpoint: "https://www.therundown.ai/rss",
    active: true,
  },
  {
    id: "x-akhaliq",
    label: "@_akhaliq (manual)",
    tier: "tier1-daily",
    cadence: "6h",
    intervalHours: 6,
    mode: "manual",
    endpoint: "https://x.com/_akhaliq",
    active: false,
  },
  {
    id: "the-batch",
    label: "The Batch",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "html",
    endpoint: "https://www.deeplearning.ai/the-batch/",
    active: true,
  },
  {
    id: "import-ai",
    label: "Import AI",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://importai.substack.com/feed",
    active: true,
  },
  {
    id: "latent-space",
    label: "Latent Space",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://www.latent.space/feed",
    active: true,
  },
  {
    id: "raschka",
    label: "Sebastian Raschka",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://magazine.sebastianraschka.com/feed",
    active: true,
  },
  {
    id: "arxiv",
    label: "arXiv AI/ML",
    tier: "tier3-research",
    cadence: "24h",
    intervalHours: 24,
    mode: "rss",
    endpoint: "https://rss.arxiv.org/rss/cs.AI+cs.LG",
    active: true,
  },
  {
    id: "hf-daily-papers",
    label: "Hugging Face Daily Papers",
    tier: "tier3-research",
    cadence: "6h",
    intervalHours: 6,
    mode: "api",
    endpoint: "https://huggingface.co/api/daily_papers",
    active: true,
  },
  {
    id: "nature-digital-medicine",
    label: "Nature Digital Medicine",
    tier: "medical-ai",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://www.nature.com/npjdigitalmed.rss",
    active: true,
  },
  {
    id: "radiology-ai",
    label: "Radiology AI",
    tier: "medical-ai",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://pubs.rsna.org/action/showFeed?type=etoc&feed=rss&jc=ai",
    active: true,
  },
  {
    id: "msr-health",
    label: "Microsoft Research Health",
    tier: "medical-ai",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://www.microsoft.com/en-us/research/blog/feed/",
    active: true,
  },
  {
    id: "moduletter",
    label: "모두레터",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 12,
    mode: "html",
    endpoint: "https://moduletter.stibee.com",
    active: true,
  },
  // Phase 1 — AI 기업 공식 블로그 (RSS direct)
  {
    id: "openai-blog",
    label: "OpenAI Blog",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://openai.com/news/rss.xml",
    active: true,
  },
  {
    id: "deepmind-blog",
    label: "Google DeepMind",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://deepmind.google/blog/rss.xml",
    active: true,
  },
  {
    id: "google-ai-blog",
    label: "Google AI Blog",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://research.google/blog/rss/",
    active: true,
  },
  {
    id: "karpathy-blog",
    label: "Andrej Karpathy",
    tier: "thought-leader",
    cadence: "weekly",
    intervalHours: 168,
    mode: "atom",
    endpoint: "https://karpathy.bearblog.dev/feed/",
    active: true,
  },
  {
    id: "dwarkesh-podcast",
    label: "Dwarkesh Podcast",
    tier: "thought-leader",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss",
    endpoint: "https://www.dwarkesh.com/feed",
    active: true,
  },
  // Phase 2 — scrape/YouTube/filter
  {
    id: "anthropic-engineering",
    label: "Anthropic Engineering",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "html",
    endpoint: "https://www.anthropic.com/engineering",
    active: true,
  },
  {
    id: "anthropic-research",
    label: "Anthropic Research",
    tier: "tier2-weekly",
    cadence: "weekly",
    intervalHours: 168,
    mode: "html",
    endpoint: "https://www.anthropic.com/research",
    active: true,
  },
  {
    id: "karpathy-youtube",
    label: "Karpathy YouTube",
    tier: "thought-leader",
    cadence: "weekly",
    intervalHours: 168,
    mode: "youtube",
    endpoint: "https://www.youtube.com/feeds/videos.xml?channel_id=UCXUPKJO5MZQN11PqgIvyuvQ",
    active: false, // YouTube RSS feed 404 — 채널 피드 비활성화됨
  },
  {
    id: "lex-fridman-ai",
    label: "Lex Fridman (AI)",
    tier: "thought-leader",
    cadence: "weekly",
    intervalHours: 168,
    mode: "rss+filter",
    endpoint: "https://lexfridman.com/feed/podcast/",
    active: true,
  },
]

export function getSourceConfig(sourceId: RadarSourceConfig["id"]): RadarSourceConfig | undefined {
  return RADAR_SOURCES.find((source) => source.id === sourceId)
}
