export const senseiData = {
  archetypes: [
    {
      name: "Roger Gracie",
      flag: "🇧🇷",
      nickname: "The GOAT",
      team: "Gracie Barra",
      stats: {
        guard: 85,
        passing: 80,
        control: 98,
        finishing: 96,
        takedowns: 70,
        legLocks: 25,
      },
      tags: ["Closed", "Mount", "CrossChoke"],
      playstyle: "Fundamental Master",
      ruleSet: "gi",
      category: "gi-legend",
      gameplan: [
        { position: "Closed", action: "힙범프 스윕", next: ["Mount"] },
        { position: "Invisible Guard", action: "미매핑 기술", next: [] },
      ],
    },
  ],
  positions: [
    {
      id: "hg",
      name: "Half Guard",
      nameKr: "하프 가드",
      layer: "guard",
      family: "half",
      perspective: "bottom",
      ruleSet: "common",
    },
    {
      id: "kshield",
      name: "Knee Shield",
      nameKr: "니쉴드",
      layer: "guard",
      family: "half",
      perspective: "bottom",
      ruleSet: "common",
    },
    {
      id: "dlr",
      name: "De La Riva",
      nameKr: "데라히바",
      layer: "guard",
      family: "open",
      perspective: "bottom",
      ruleSet: "common",
    },
    {
      id: "xg",
      name: "X Guard",
      nameKr: "엑스 가드",
      layer: "guard",
      family: "open",
      perspective: "bottom",
      ruleSet: "common",
    },
    {
      id: "kimura",
      name: "Kimura",
      nameKr: "기무라",
      layer: "submission",
      perspective: "neutral",
      ruleSet: "common",
    },
    {
      id: "hq",
      name: "Headquarters",
      nameKr: "본부 자세",
      layer: "passing",
      perspective: "top",
      ruleSet: "common",
    },
    {
      id: "kcp",
      name: "Knee Cut Pass",
      nameKr: "니슬라이드",
      layer: "passing",
      perspective: "top",
      ruleSet: "common",
    },
    {
      id: "smash",
      name: "Smash Pass",
      nameKr: "스매시",
      layer: "passing",
      perspective: "top",
      ruleSet: "common",
    },
    {
      id: "side_top",
      name: "Side Control",
      nameKr: "사이드 컨트롤",
      layer: "control",
      perspective: "top",
      lessonNumbers: [2],
      ruleSet: "common",
    },
    {
      id: "side_bottom",
      name: "Side (bottom)",
      nameKr: "사이드 당함",
      layer: "control",
      perspective: "bottom",
      lessonNumbers: [1],
      ruleSet: "common",
    },
    {
      id: "kob_top",
      name: "Knee on Belly",
      nameKr: "니온벨리",
      layer: "control",
      perspective: "top",
      lessonNumbers: [18],
      ruleSet: "common",
    },
    {
      id: "kob_bottom",
      name: "KoB (bottom)",
      nameKr: "니온벨리 당함",
      layer: "control",
      perspective: "bottom",
      lessonNumbers: [19],
      ruleSet: "common",
    },
    {
      id: "mount_top",
      name: "Mount",
      nameKr: "마운트",
      layer: "control",
      perspective: "top",
      lessonNumbers: [38],
      ruleSet: "common",
    },
    {
      id: "mount_bottom",
      name: "Mount (bottom)",
      nameKr: "마운트 당함",
      layer: "control",
      perspective: "bottom",
      lessonNumbers: [42],
      ruleSet: "common",
    },
    {
      id: "back_top",
      name: "Back Control",
      nameKr: "백 컨트롤",
      layer: "control",
      perspective: "top",
      lessonNumbers: [51],
      ruleSet: "common",
    },
    {
      id: "back_bottom",
      name: "Back (defending)",
      nameKr: "백 당함",
      layer: "control",
      perspective: "bottom",
      lessonNumbers: [52],
      ruleSet: "common",
    },
    {
      id: "turtle_top",
      name: "Turtle (attacking)",
      nameKr: "터틀 공격",
      layer: "control",
      perspective: "top",
      lessonNumbers: [54],
      ruleSet: "common",
    },
    {
      id: "turtle_bottom",
      name: "Turtle (defending)",
      nameKr: "터틀 방어",
      layer: "control",
      perspective: "bottom",
      lessonNumbers: [56],
      ruleSet: "common",
    },
  ],
  transitions: [
    {
      from: "kshield",
      to: "hg",
      action: "언더훅 회복",
      actionEn: "Recover underhook",
      condition: "상대가 니쉴드를 누를 때",
      type: "transition",
      ruleSet: "common",
    },
    {
      from: "hg",
      to: "dlr",
      action: "데라히바 전환",
      actionEn: "Transition to DLR",
      condition: "상대가 일어설 때",
      type: "transition",
      ruleSet: "common",
    },
    {
      from: "dlr",
      to: "xg",
      action: "엑스가드 진입",
      actionEn: "Enter X guard",
      type: "transition",
      ruleSet: "common",
    },
    {
      from: "mount_bottom",
      to: "hg",
      action: "브릿지 이스케이프",
      actionEn: "Bridge Escape",
      type: "escape",
      ruleSet: "common",
    },
  ],
}
