import type { Archetype } from "@/lib/types/sensei"

export const ARCHETYPES: Archetype[] = [
  // ===== Gi Legends =====
  {
    name: "Roger Gracie",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The GOAT",
    team: "Gracie Barra",
    stats: { guard: 85, passing: 80, control: 98, finishing: 96, takedowns: 70, legLocks: 25 },
    tags: ["Closed", "Mount", "S-Mount", "CrossChoke", "RNC", "ArmB", "KCP"],
    playstyle: "Fundamental Master",
    ruleSet: "gi",
    category: "gi-legend",
  },
  {
    name: "Leandro Lo",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "King of Passing",
    team: "NS Brotherhood",
    stats: { guard: 82, passing: 96, control: 85, finishing: 78, takedowns: 88, legLocks: 30 },
    tags: ["Torreando", "KCP", "Spider", "Open", "Takedown", "SingleLeg"],
    playstyle: "Dynamic Passer",
    ruleSet: "gi",
    category: "gi-legend",
  },
  {
    name: "Marcelo Garcia",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Legend",
    team: "MGA",
    stats: { guard: 92, passing: 75, control: 78, finishing: 90, takedowns: 68, legLocks: 38 },
    tags: ["Butterfly", "XG", "SLX", "BackTake", "RNC", "Guillotine", "ArmDrag"],
    playstyle: "Dynamic Guard / Back Taker",
    ruleSet: "gi",
    category: "gi-legend",
  },
  {
    name: "Rafa Mendes",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Innovator",
    team: "AOJ",
    stats: { guard: 90, passing: 82, control: 80, finishing: 85, takedowns: 72, legLocks: 42 },
    tags: ["DLR", "RDLR", "Bolo", "BackTake", "RNC", "KCP"],
    playstyle: "Berimbolo Innovator",
    ruleSet: "gi",
    category: "gi-legend",
  },
  {
    name: "Lucas Leite",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "Coyote Master",
    team: "Checkmat",
    stats: { guard: 92, passing: 65, control: 72, finishing: 65, takedowns: 55, legLocks: 35 },
    tags: ["HG", "KShield", "Sit-up", "SingleSweep", "BackTake"],
    playstyle: "Coyote Half Guard",
    ruleSet: "gi",
    category: "gi-legend",
  },
  {
    name: "Lucas Lepri",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Professor",
    team: "Alliance",
    stats: { guard: 78, passing: 95, control: 85, finishing: 75, takedowns: 72, legLocks: 30 },
    tags: ["KShield", "KCP", "Torreando", "BackTake", "RNC"],
    playstyle: "Precision Passer",
    ruleSet: "gi",
    category: "gi-legend",
  },
  {
    name: "Bernardo Faria",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "Pressure Cooker",
    team: "Alliance",
    stats: { guard: 88, passing: 92, control: 82, finishing: 62, takedowns: 55, legLocks: 22 },
    tags: ["DHG", "HG", "SingleSweep", "Smash", "Stack"],
    playstyle: "Deep Half / Pressure Pass",
    ruleSet: "gi",
    category: "gi-legend",
  },
  {
    name: "Romulo Barral",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "Spider King",
    team: "Gracie Barra",
    stats: { guard: 90, passing: 78, control: 80, finishing: 82, takedowns: 65, legLocks: 28 },
    tags: ["Spider", "Lasso", "Triangle", "Omo", "BackTake"],
    playstyle: "Spider Guard Master",
    ruleSet: "gi",
    category: "gi-legend",
  },

  // ===== Gi Active =====
  {
    name: "Mica Galvao",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Prodigy",
    team: "Melqui Galvao",
    stats: { guard: 90, passing: 85, control: 88, finishing: 95, takedowns: 82, legLocks: 68 },
    tags: ["DLR", "BackTake", "RNC", "ArmB", "Guillotine", "Takedown", "SingleLeg", "KCP", "Bolo"],
    playstyle: "Explosive All-Rounder",
    ruleSet: "both",
    category: "gi-active",
  },
  {
    name: "Tainan Dalpra",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Machine",
    team: "AOJ",
    stats: { guard: 82, passing: 95, control: 88, finishing: 80, takedowns: 70, legLocks: 42 },
    tags: ["DLR", "RDLR", "KCP", "LongStep", "Torreando", "BackTake", "Mount", "RNC", "Bolo"],
    playstyle: "Systematic Passer",
    ruleSet: "gi",
    category: "gi-active",
  },
  {
    name: "Diego Pato",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Scrambler",
    team: "AOJ",
    stats: { guard: 80, passing: 78, control: 72, finishing: 82, takedowns: 78, legLocks: 82 },
    tags: ["SLX", "XG", "Ashi", "IHH", "ToeHold", "Takedown", "Butterfly", "BackTake", "Guillotine"],
    playstyle: "Dynamic Scrambler",
    ruleSet: "both",
    category: "gi-active",
  },
  {
    name: "Mayssa Bastos",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Queen",
    team: "AOJ",
    stats: { guard: 95, passing: 72, control: 68, finishing: 85, takedowns: 55, legLocks: 58 },
    tags: ["Closed", "DLR", "Spider", "ArmB", "Triangle", "Omo", "Bolo", "RDLR", "BackTake"],
    playstyle: "Guard Specialist",
    ruleSet: "gi",
    category: "gi-active",
  },
  {
    name: "Adam Wardzinski",
    flag: "\ud83c\uddf5\ud83c\uddf1",
    nickname: "Butterfly King",
    team: "Checkmat",
    stats: { guard: 92, passing: 82, control: 68, finishing: 70, takedowns: 60, legLocks: 52 },
    tags: ["Butterfly", "SingleSweep", "HipSweep", "XG", "SLX", "KCP", "Smash", "BackTake", "Kimura"],
    playstyle: "Butterfly Guard Master",
    ruleSet: "gi",
    category: "gi-active",
  },

  // ===== No-Gi =====
  {
    name: "Gordon Ryan",
    flag: "\ud83c\uddfa\ud83c\uddf8",
    nickname: "The King",
    team: "Kingsway",
    stats: { guard: 82, passing: 96, control: 95, finishing: 92, takedowns: 78, legLocks: 88 },
    tags: ["Butterfly", "BackTake", "RNC", "Mount", "KCP", "Torreando", "IHH", "Ashi", "Smash"],
    playstyle: "Dominant All-Rounder",
    ruleSet: "nogi",
    category: "nogi",
  },
  {
    name: "Kade Ruotolo",
    flag: "\ud83c\uddfa\ud83c\uddf8",
    nickname: "The Phenom",
    team: "Atos",
    stats: { guard: 78, passing: 80, control: 80, finishing: 90, takedowns: 85, legLocks: 75 },
    tags: ["Darce", "RNC", "Guillotine", "BackTake", "Takedown", "SingleLeg", "Butterfly", "Ashi", "IHH"],
    playstyle: "Relentless Attacker",
    ruleSet: "nogi",
    category: "nogi",
  },
  {
    name: "Mikey Musumeci",
    flag: "\ud83c\uddfa\ud83c\uddf8",
    nickname: "The Scientist",
    team: "Independent",
    stats: { guard: 98, passing: 52, control: 42, finishing: 78, takedowns: 30, legLocks: 95 },
    tags: ["DLR", "SLX", "RDLR", "IHH", "OHH", "Ashi", "Saddle", "50/50", "Estima"],
    playstyle: "Guard Wizard / Leg Locker",
    ruleSet: "nogi",
    category: "nogi",
  },
  {
    name: "Cole Abate",
    flag: "\ud83c\uddfa\ud83c\uddf8",
    nickname: "Rising Star",
    team: "AOJ",
    stats: { guard: 80, passing: 85, control: 82, finishing: 88, takedowns: 72, legLocks: 78 },
    tags: ["BackTake", "RNC", "KCP", "LongStep", "DLR", "SLX", "Ashi", "IHH", "Takedown"],
    playstyle: "Complete Grappler",
    ruleSet: "nogi",
    category: "nogi",
  },
  {
    name: "Kaynan Duarte",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Tank",
    team: "Atos",
    stats: { guard: 68, passing: 92, control: 95, finishing: 88, takedowns: 85, legLocks: 62 },
    tags: ["Mount", "KoB", "Smash", "Stack", "RNC", "ArmB", "Takedown", "DoubleLeg", "Bodylock"],
    playstyle: "Pressure Monster",
    ruleSet: "nogi",
    category: "nogi",
  },
  {
    name: "Diogo Reis",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "Baby Shark",
    team: "Melqui Galvao",
    stats: { guard: 85, passing: 75, control: 72, finishing: 82, takedowns: 75, legLocks: 82 },
    tags: ["SLX", "XG", "Ashi", "IHH", "OHH", "BackTake", "Guillotine", "Takedown", "Butterfly"],
    playstyle: "Dynamic Scrambler",
    ruleSet: "nogi",
    category: "nogi",
  },
  {
    name: "Craig Jones",
    flag: "\ud83c\udde6\ud83c\uddfa",
    nickname: "The Leg Hunter",
    team: "Independent",
    stats: { guard: 72, passing: 55, control: 52, finishing: 80, takedowns: 48, legLocks: 98 },
    tags: ["KShield", "SLX", "XG", "Ashi", "Saddle", "IHH", "OHH", "KneeBar", "ToeHold"],
    playstyle: "Leg Lock Specialist",
    ruleSet: "nogi",
    category: "nogi",
  },

  // ===== Special =====
  {
    name: "\uc870\uc900\uc6a9",
    flag: "\ud83c\uddf0\ud83c\uddf7",
    nickname: "My Sensei",
    team: "DT Wire",
    stats: { guard: 85, passing: 70, control: 72, finishing: 68, takedowns: 60, legLocks: 48 },
    tags: ["HG", "KShield", "Sit-up", "SingleSweep", "HipSweep", "Mount", "BackTake", "RNC", "KCP"],
    playstyle: "Coyote Half Guard Specialist",
    ruleSet: "gi",
    category: "special",
    isCustom: true,
    editableStats: true,
    styleReferences: ["Lucas Leite", "Lucas Lepri"],
    bio: "30\uc138, \ube14\ub799\ubca8\ud2b8(2018~), \ud398\ub354\uae09. 2026 IBJJF European 3\uc704. \ucf54\uc694\ud14c\ud558\ud504/\uc2ef\uc5c5 \uc704\uc8fc.",
  },
]
