import type { Archetype } from "@/lib/types/sensei"

export const ARCHETYPES: Archetype[] = [
  // ===== Gi Legends =====
  {
    name: "Roger Gracie",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The GOAT",
    team: "Gracie Barra",
    stats: { guard: 85, passing: 80, control: 98, finishing: 96, takedowns: 70, legLocks: 25 },
    tags: ["Closed", "Mount", "S-Mount", "CrossChoke", "RNC", "ArmB", "KCP"],
    playstyle: "Fundamental Master",
    ruleSet: "gi",
    category: "gi-legend",
    gameplan: [
      { position: "Closed", action: "클로즈드 가드에서 크로스 칼라 그립 확보", next: ["Mount", "BackTake"] },
      { position: "Mount", action: "마운트 → S-마운트 전환, 크로스 초크 위협", next: ["S-Mount"] },
      { position: "S-Mount", action: "크로스 칼라 초크 or 암바 피니쉬", next: [] },
      { position: "BackTake", action: "백 컨트롤 → RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Leandro Lo",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "King of Passing",
    team: "NS Brotherhood",
    stats: { guard: 82, passing: 96, control: 85, finishing: 78, takedowns: 88, legLocks: 30 },
    tags: ["Torreando", "KCP", "Spider", "Open", "Takedown", "SingleLeg"],
    playstyle: "Dynamic Passer",
    ruleSet: "gi",
    category: "gi-legend",
    gameplan: [
      { position: "Open", action: "스탠딩에서 그립 파이팅 → 토헤안도 진입", next: ["Torreando", "KCP"] },
      { position: "Torreando", action: "토헤안도 패스로 사이드 확보", next: ["SideCtrl"] },
      { position: "KCP", action: "니컷 패스 → 사이드 or 마운트", next: ["SideCtrl", "Mount"] },
      { position: "SideCtrl", action: "백테이크 or 마운트 전환", next: ["BackTake", "Mount"] },
      { position: "BackTake", action: "RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Marcelo Garcia",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Legend",
    team: "MGA",
    stats: { guard: 92, passing: 75, control: 78, finishing: 90, takedowns: 68, legLocks: 38 },
    tags: ["Butterfly", "XG", "SLX", "BackTake", "RNC", "Guillotine", "ArmDrag"],
    playstyle: "Dynamic Guard / Back Taker",
    ruleSet: "gi",
    category: "gi-legend",
    gameplan: [
      { position: "Butterfly", action: "버터플라이에서 암드래그 or X가드 진입", next: ["BackTake", "XG"] },
      { position: "XG", action: "X가드 스윕 → 탑 포지션", next: ["BackTake", "SideCtrl"] },
      { position: "BackTake", action: "시트벨트 그립 → RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Rafa Mendes",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Innovator",
    team: "AOJ",
    stats: { guard: 90, passing: 82, control: 80, finishing: 85, takedowns: 72, legLocks: 42 },
    tags: ["DLR", "RDLR", "Bolo", "BackTake", "RNC", "KCP"],
    playstyle: "Berimbolo Innovator",
    ruleSet: "gi",
    category: "gi-legend",
    gameplan: [
      { position: "DLR", action: "드라히바에서 베림볼로 진입", next: ["Bolo"] },
      { position: "Bolo", action: "베림볼로 인버트 → 백 확보", next: ["BackTake"] },
      { position: "BackTake", action: "칼라 그립 → RNC or 초크 피니쉬", next: [] },
    ],
  },
  {
    name: "Lucas Leite",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "Coyote Master",
    team: "Checkmat",
    stats: { guard: 92, passing: 65, control: 72, finishing: 65, takedowns: 55, legLocks: 35 },
    tags: ["HG", "KShield", "Sit-up", "SingleSweep", "BackTake"],
    playstyle: "Coyote Half Guard",
    ruleSet: "gi",
    category: "gi-legend",
    gameplan: [
      { position: "HG", action: "하프가드에서 언더훅 확보 → 코요테 셋업", next: ["Sit-up"] },
      { position: "Sit-up", action: "싯업 가드 → 싱글레그 스윕", next: ["SingleSweep"] },
      { position: "SingleSweep", action: "스윕 성공 → 백테이크", next: ["BackTake"] },
      { position: "BackTake", action: "RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Lucas Lepri",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Professor",
    team: "Alliance",
    stats: { guard: 78, passing: 95, control: 85, finishing: 75, takedowns: 72, legLocks: 30 },
    tags: ["KShield", "KCP", "Torreando", "BackTake", "RNC"],
    playstyle: "Precision Passer",
    ruleSet: "gi",
    category: "gi-legend",
    gameplan: [
      { position: "KShield", action: "니쉴드에서 프레임 확보 → 가드 리커버리", next: ["KCP"] },
      { position: "KCP", action: "정밀한 니컷 패스 → 사이드 컨트롤", next: ["SideCtrl"] },
      { position: "SideCtrl", action: "백테이크 전환", next: ["BackTake"] },
      { position: "BackTake", action: "RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Bernardo Faria",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "Pressure Cooker",
    team: "Alliance",
    stats: { guard: 88, passing: 92, control: 82, finishing: 62, takedowns: 55, legLocks: 22 },
    tags: ["DHG", "HG", "SingleSweep", "Smash", "Stack"],
    playstyle: "Deep Half / Pressure Pass",
    ruleSet: "gi",
    category: "gi-legend",
    gameplan: [
      { position: "DHG", action: "딥하프 진입 → 싱글레그 스윕", next: ["SingleSweep"] },
      { position: "SingleSweep", action: "스윕 → 탑 포지션 확보", next: ["Smash", "Stack"] },
      { position: "Smash", action: "스매시 패스 → 사이드 프레셔", next: ["SideCtrl"] },
      { position: "Stack", action: "스택 패스 → 사이드 컨트롤", next: ["SideCtrl"] },
    ],
  },
  {
    name: "Romulo Barral",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "Spider King",
    team: "Gracie Barra",
    stats: { guard: 90, passing: 78, control: 80, finishing: 82, takedowns: 65, legLocks: 28 },
    tags: ["Spider", "Lasso", "Triangle", "Omo", "BackTake"],
    playstyle: "Spider Guard Master",
    ruleSet: "gi",
    category: "gi-legend",
    gameplan: [
      { position: "Spider", action: "스파이더 가드에서 라쏘 전환 or 스윕", next: ["Lasso", "Mount"] },
      { position: "Lasso", action: "라쏘 → 트라이앵글 or 오모플라타 셋업", next: ["Triangle", "Omo"] },
      { position: "Triangle", action: "트라이앵글 초크 피니쉬", next: [] },
      { position: "Omo", action: "오모플라타 → 스윕 or 서브미션", next: [] },
    ],
  },

  // ===== Gi Active =====
  {
    name: "Mica Galvao",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Prodigy",
    team: "Melqui Galvao",
    stats: { guard: 90, passing: 85, control: 88, finishing: 95, takedowns: 82, legLocks: 68 },
    tags: ["DLR", "BackTake", "RNC", "ArmB", "Guillotine", "Takedown", "SingleLeg", "KCP", "Bolo"],
    playstyle: "Explosive All-Rounder",
    ruleSet: "both",
    category: "gi-active",
    gameplan: [
      { position: "DLR", action: "드라히바에서 베림볼로 or 스윕", next: ["Bolo", "BackTake"] },
      { position: "Bolo", action: "베림볼로 → 백테이크", next: ["BackTake"] },
      { position: "Takedown", action: "폭발적 테이크다운 → 탑 컨트롤", next: ["KCP", "Mount"] },
      { position: "BackTake", action: "RNC or 암바 피니쉬", next: [] },
    ],
  },
  {
    name: "Tainan Dalpra",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Machine",
    team: "AOJ",
    stats: { guard: 82, passing: 95, control: 88, finishing: 80, takedowns: 70, legLocks: 42 },
    tags: ["DLR", "RDLR", "KCP", "LongStep", "Torreando", "BackTake", "Mount", "RNC", "Bolo"],
    playstyle: "Systematic Passer",
    ruleSet: "gi",
    category: "gi-active",
    gameplan: [
      { position: "DLR", action: "드라히바에서 체계적 패스 셋업", next: ["KCP", "LongStep"] },
      { position: "KCP", action: "니컷 패스 → 마운트", next: ["Mount"] },
      { position: "LongStep", action: "롱스텝 패스 → 사이드 → 백테이크", next: ["BackTake"] },
      { position: "Mount", action: "마운트에서 RNC 셋업 → 백테이크", next: ["BackTake"] },
      { position: "BackTake", action: "RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Diego Pato",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Scrambler",
    team: "AOJ",
    stats: { guard: 80, passing: 78, control: 72, finishing: 82, takedowns: 78, legLocks: 82 },
    tags: ["SLX", "XG", "Ashi", "IHH", "ToeHold", "Takedown", "Butterfly", "BackTake", "Guillotine"],
    playstyle: "Dynamic Scrambler",
    ruleSet: "both",
    category: "gi-active",
    gameplan: [
      { position: "Butterfly", action: "버터플라이 → SLX 전환", next: ["SLX"] },
      { position: "SLX", action: "SLX → 레그 엔탱글먼트 or 스윕", next: ["Ashi", "BackTake"] },
      { position: "Ashi", action: "아시가라미 → 힐훅 or 토홀드", next: [] },
      { position: "BackTake", action: "기요틴 or RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Mayssa Bastos",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Queen",
    team: "AOJ",
    stats: { guard: 95, passing: 72, control: 68, finishing: 85, takedowns: 55, legLocks: 58 },
    tags: ["Closed", "DLR", "Spider", "ArmB", "Triangle", "Omo", "Bolo", "RDLR", "BackTake"],
    playstyle: "Guard Specialist",
    ruleSet: "gi",
    category: "gi-active",
    gameplan: [
      { position: "DLR", action: "드라히바에서 베림볼로 or 스윕", next: ["Bolo", "BackTake"] },
      { position: "Closed", action: "클로즈드에서 암바 or 트라이앵글 셋업", next: ["ArmB", "Triangle"] },
      { position: "Bolo", action: "베림볼로 → 백테이크", next: ["BackTake"] },
      { position: "BackTake", action: "초크 피니쉬", next: [] },
    ],
  },
  {
    name: "Adam Wardzinski",
    flag: "\ud83c\uddf5\ud83c\uddf1",
    nickname: "Butterfly King",
    team: "Checkmat",
    stats: { guard: 92, passing: 82, control: 68, finishing: 70, takedowns: 60, legLocks: 52 },
    tags: ["Butterfly", "SingleSweep", "HipSweep", "XG", "SLX", "KCP", "Smash", "BackTake", "Kimura"],
    playstyle: "Butterfly Guard Master",
    ruleSet: "gi",
    category: "gi-active",
    gameplan: [
      { position: "Butterfly", action: "버터플라이에서 힙 스윕 or X가드 진입", next: ["HipSweep", "XG"] },
      { position: "XG", action: "X가드 → 싱글레그 스윕", next: ["SingleSweep"] },
      { position: "HipSweep", action: "스윕 → 탑 → 스매시 패스", next: ["Smash", "KCP"] },
      { position: "Smash", action: "스매시 패스 → 사이드 → 기무라", next: [] },
    ],
  },

  // ===== No-Gi =====
  {
    name: "Gordon Ryan",
    flag: "\ud83c\uddfa\ud83c\uddf8",
    nickname: "The King",
    team: "Kingsway",
    stats: { guard: 82, passing: 96, control: 95, finishing: 92, takedowns: 78, legLocks: 88 },
    tags: ["Butterfly", "BackTake", "RNC", "Mount", "KCP", "Torreando", "IHH", "Ashi", "Smash"],
    playstyle: "Dominant All-Rounder",
    ruleSet: "nogi",
    category: "nogi",
    gameplan: [
      { position: "Butterfly", action: "숄더 크런치 → 스윕 or 패스 셋업", next: ["KCP", "Torreando"] },
      { position: "KCP", action: "니컷 패스 → 마운트", next: ["Mount"] },
      { position: "Mount", action: "마운트에서 암바 or 백테이크", next: ["BackTake", "ArmB"] },
      { position: "BackTake", action: "바디 트라이앵글 → RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Kade Ruotolo",
    flag: "\ud83c\uddfa\ud83c\uddf8",
    nickname: "The Phenom",
    team: "Atos",
    stats: { guard: 78, passing: 80, control: 80, finishing: 90, takedowns: 85, legLocks: 75 },
    tags: ["Darce", "RNC", "Guillotine", "BackTake", "Takedown", "SingleLeg", "Butterfly", "Ashi", "IHH"],
    playstyle: "Relentless Attacker",
    ruleSet: "nogi",
    category: "nogi",
    gameplan: [
      { position: "Takedown", action: "싱글레그 테이크다운 → 탑 프레셔", next: ["SideCtrl", "BackTake"] },
      { position: "SideCtrl", action: "사이드에서 다스 초크 셋업", next: ["Darce"] },
      { position: "Darce", action: "다스 초크 피니쉬", next: [] },
      { position: "BackTake", action: "RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Mikey Musumeci",
    flag: "\ud83c\uddfa\ud83c\uddf8",
    nickname: "The Scientist",
    team: "Independent",
    stats: { guard: 98, passing: 52, control: 42, finishing: 78, takedowns: 30, legLocks: 95 },
    tags: ["DLR", "SLX", "RDLR", "IHH", "OHH", "Ashi", "Saddle", "50/50", "Estima"],
    playstyle: "Guard Wizard / Leg Locker",
    ruleSet: "nogi",
    category: "nogi",
    gameplan: [
      { position: "DLR", action: "드라히바에서 SLX 진입", next: ["SLX"] },
      { position: "SLX", action: "SLX → 레그 엔탱글먼트", next: ["Ashi", "Saddle"] },
      { position: "Ashi", action: "아시가라미 → 새들 전환", next: ["Saddle"] },
      { position: "Saddle", action: "인사이드 힐훅 피니쉬", next: [] },
    ],
  },
  {
    name: "Cole Abate",
    flag: "\ud83c\uddfa\ud83c\uddf8",
    nickname: "Rising Star",
    team: "AOJ",
    stats: { guard: 80, passing: 85, control: 82, finishing: 88, takedowns: 72, legLocks: 78 },
    tags: ["BackTake", "RNC", "KCP", "LongStep", "DLR", "SLX", "Ashi", "IHH", "Takedown"],
    playstyle: "Complete Grappler",
    ruleSet: "nogi",
    category: "nogi",
    gameplan: [
      { position: "DLR", action: "드라히바에서 백테이크 셋업", next: ["BackTake", "SLX"] },
      { position: "SLX", action: "SLX → 아시 진입 → 힐훅", next: ["Ashi"] },
      { position: "BackTake", action: "백 컨트롤 → RNC 피니쉬", next: [] },
      { position: "Ashi", action: "힐훅 피니쉬", next: [] },
    ],
  },
  {
    name: "Kaynan Duarte",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "The Tank",
    team: "Atos",
    stats: { guard: 68, passing: 92, control: 95, finishing: 88, takedowns: 85, legLocks: 62 },
    tags: ["Mount", "KoB", "Smash", "Stack", "RNC", "ArmB", "Takedown", "DoubleLeg", "Bodylock"],
    playstyle: "Pressure Monster",
    ruleSet: "nogi",
    category: "nogi",
    gameplan: [
      { position: "Takedown", action: "더블레그 or 바디락 테이크다운", next: ["Smash", "Stack"] },
      { position: "Smash", action: "스매시 패스 → 마운트", next: ["Mount"] },
      { position: "Mount", action: "마운트 프레셔 → 암바 or RNC", next: ["ArmB", "BackTake"] },
      { position: "BackTake", action: "RNC 피니쉬", next: [] },
    ],
  },
  {
    name: "Diogo Reis",
    flag: "\ud83c\udde7\ud83c\uddf7",
    nickname: "Baby Shark",
    team: "Melqui Galvao",
    stats: { guard: 85, passing: 75, control: 72, finishing: 82, takedowns: 75, legLocks: 82 },
    tags: ["SLX", "XG", "Ashi", "IHH", "OHH", "BackTake", "Guillotine", "Takedown", "Butterfly"],
    playstyle: "Dynamic Scrambler",
    ruleSet: "nogi",
    category: "nogi",
    gameplan: [
      { position: "Butterfly", action: "버터플라이에서 SLX 전환", next: ["SLX"] },
      { position: "SLX", action: "SLX → 아시 or 스윕", next: ["Ashi", "BackTake"] },
      { position: "Ashi", action: "힐훅 or 토홀드 피니쉬", next: [] },
      { position: "BackTake", action: "기요틴 셋업 → 피니쉬", next: [] },
    ],
  },
  {
    name: "Craig Jones",
    flag: "\ud83c\udde6\ud83c\uddfa",
    nickname: "The Leg Hunter",
    team: "Independent",
    stats: { guard: 72, passing: 55, control: 52, finishing: 80, takedowns: 48, legLocks: 98 },
    tags: ["KShield", "SLX", "XG", "Ashi", "Saddle", "IHH", "OHH", "KneeBar", "ToeHold"],
    playstyle: "Leg Lock Specialist",
    ruleSet: "nogi",
    category: "nogi",
    gameplan: [
      { position: "KShield", action: "니쉴드에서 SLX 진입", next: ["SLX"] },
      { position: "SLX", action: "SLX → 아시가라미 → 새들", next: ["Ashi", "Saddle"] },
      { position: "Ashi", action: "아시 → 힐훅 or 니바", next: [] },
      { position: "Saddle", action: "새들에서 인사이드 힐훅 피니쉬", next: [] },
    ],
  },

  // ===== Special =====
  {
    name: "\uc870\uc900\uc6a9",
    flag: "\ud83c\uddf0\ud83c\uddf7",
    nickname: "My Sensei",
    team: "DT Wire",
    stats: { guard: 85, passing: 70, control: 72, finishing: 68, takedowns: 60, legLocks: 48 },
    tags: ["HG", "KShield", "Sit-up", "SingleSweep", "HipSweep", "Mount", "BackTake", "RNC", "KCP"],
    playstyle: "Coyote Half Guard Specialist",
    ruleSet: "gi",
    category: "special",
    isCustom: true,
    editableStats: true,
    styleReferences: ["Lucas Leite", "Lucas Lepri"],
    bio: "30\uc138, \ube14\ub799\ubca8\ud2b8(2018~), \ud398\ub354\uae09. 2026 IBJJF European 3\uc704. \ucf54\uc694\ud14c\ud558\ud504/\uc2ef\uc5c5 \uc704\uc8fc.",
    gameplan: [
      { position: "HG", action: "하프가드 언더훅 → 코요테/싯업 전환", next: ["Sit-up"] },
      { position: "Sit-up", action: "싱글레그 스윕 or 힙 스윕", next: ["SingleSweep", "HipSweep"] },
      { position: "SingleSweep", action: "스윕 → 마운트 or 백테이크", next: ["Mount", "BackTake"] },
      { position: "Mount", action: "마운트에서 RNC 셋업", next: ["BackTake"] },
      { position: "BackTake", action: "RNC 피니쉬", next: [] },
    ],
  },
]
