export const POSITION_EVIDENCE_ALIASES: Readonly<Record<string, readonly string[]>> = {
  hg: ["half guard", "halfguard", "하프", "하프가드"],
  kshield: ["knee shield", "kneeshield", "니쉴드", "니실드"],
  situp: ["sit-up", "situp", "싯업", "시트업"],
  closed: ["closed guard", "closedguard", "클로즈", "클로즈드 가드"],
  butterfly: ["butterfly guard", "버터플라이", "버터플라이 가드"],
  dlr: ["de la riva", "데라히바"],
  rdlr: ["reverse de la riva", "리버스 데라히바"],
  back_top: ["back control", "back", "백 컨트롤", "백"],
  mount_top: ["mount", "마운트"],
  side_top: ["side control", "사이드 컨트롤", "사이드"],
  turtle_top: ["turtle", "터틀"],
  ns_top: ["north south", "north-south", "노스사우스"],
  hq: ["headquarters", "본부", "본부 자세"],
  kcp: ["knee cut", "knee slice", "니컷", "니 슬라이드"],
  smash: ["smash pass", "스매시 패스"],
  halfpass: ["half guard pass", "half pass", "하프 패스", "하프가드 패스"],
}

export const FINISH_EVIDENCE_ALIASES: Readonly<Record<string, readonly string[]>> = {
  armb: ["armb", "armbar", "straight armbar", "암바", "스트레이트 암바"],
  bowarrow: [
    "bow and arrow",
    "bow-and-arrow",
    "bowarrow",
    "보우앤아로우",
    "보우앤애로우",
    "보앤아로우",
    "보앤애로우",
    "보우 앤 애로우",
  ],
  kimura: ["kimura", "기무라", "키무라"],
  triangle: ["triangle", "triangle choke", "삼각", "삼각초크"],
  guillotine: ["guillotine", "길로틴"],
  darce: ["d'arce", "darce", "다스"],
  rnc: ["rear naked choke", "rnc", "리어네이키드 초크"],
  crosschoke: ["cross choke", "crosschoke", "크로스 초크"],
  ezekiel: ["ezekiel", "이지키엘"],
  americana: ["americana", "아메리카나"],
}
