import type { FollowedEvent } from "@/lib/types/sensei"

// 2026-08-17 기준 공식 국제 단체 캘린더로 확인한 주요·아시아권 일정.
export const INTERNATIONAL_FOLLOWED_EVENTS: FollowedEvent[] = [
  {
    id: "intl-ajp-moscow-2026",
    name: "Abu Dhabi Grand Slam Moscow",
    date: "2026-08-29",
    location: "Moscow, Russia",
    organization: "AJP",
    ruleSet: "gi",
    type: "major",
    notes: "국제 · 8월 29~30일",
    url: "https://ajptour.com/en/event/1474",
  },
  {
    id: "intl-sjjif-world-gi-2026",
    name: "SJJIF World Jiu Jitsu Championship",
    date: "2026-09-03",
    location: "Tokyo, Japan",
    organization: "SJJIF · ASJJF",
    ruleSet: "gi",
    type: "major",
    notes: "국제 · 9월 3~6일 · 접수 마감",
    url: "https://asjjf.org/main/eventInfo/1843",
  },
  {
    id: "intl-sjjif-world-nogi-2026",
    name: "SJJIF World No-Gi Championship",
    date: "2026-09-03",
    location: "Tokyo, Japan",
    organization: "SJJIF · ASJJF",
    ruleSet: "nogi",
    type: "major",
    notes: "국제 · 9월 3~6일 · 접수 마감",
    url: "https://asjjf.org/main/eventInfo/1844",
  },
  {
    id: "intl-jiujitsu-con-gi-2026",
    name: "Jiu-Jitsu CON International",
    date: "2026-09-03",
    location: "Las Vegas, USA",
    organization: "IBJJF",
    ruleSet: "gi",
    type: "major",
    notes: "국제 · 접수 8월 23일 마감",
    url: "https://ibjjf.com/events/jiu-jitsu-con-international-2026",
  },
  {
    id: "intl-ajp-asia-2026",
    name: "AJP Tour Asia Continental Championship",
    date: "2026-09-04",
    location: "Abu Dhabi, UAE",
    organization: "AJP",
    ruleSet: "gi",
    type: "major",
    notes: "국제 · 아시아 컨티넨털 · 9월 4~6일",
    url: "https://ajptour.com/en/event/1407",
  },
  {
    id: "intl-ibjjf-kuala-lumpur-2026",
    name: "Kuala Lumpur International Open",
    date: "2026-09-19",
    location: "Cyberjaya, Malaysia",
    organization: "IBJJF",
    ruleSet: "both",
    type: "major",
    notes: "국제 · 9월 19~20일 · 접수 9월 11일 마감",
    url: "https://ibjjf.com/events/kuala-lumpur-international-open-ibjjf-jiu-jitsu-championship-2026",
  },
  {
    id: "intl-asjjf-taiwan-2026",
    name: "ASJJF Taiwan International",
    date: "2026-09-19",
    location: "Taipei, Taiwan",
    organization: "ASJJF",
    ruleSet: "both",
    type: "major",
    notes: "국제 · 9월 19~20일 · 접수 9월 9일 마감",
    url: "https://asjjf.org/main/eventInfo/1957",
  },
  {
    id: "intl-adcc-singapore-2026",
    name: "ADCC Singapore Open",
    date: "2026-10-11",
    location: "Singapore",
    organization: "ADCC",
    ruleSet: "nogi",
    type: "major",
    notes: "국제 · 아시아권 ADCC Open",
    url: "https://smoothcomp.com/en/event/34049",
  },
  {
    id: "intl-ajp-shanghai-nogi-2026",
    name: "AJP No-Gi Shanghai International",
    date: "2026-10-16",
    location: "Shanghai, China",
    organization: "AJP",
    ruleSet: "nogi",
    type: "major",
    notes: "국제 · 아시아권",
    url: "https://ajptour.com/en/event/1562",
  },
  {
    id: "intl-pan-pacific-2026",
    name: "Pan Pacific IBJJF Championship",
    date: "2026-10-16",
    location: "Melbourne, Australia",
    organization: "IBJJF",
    ruleSet: "both",
    type: "major",
    notes: "국제 · 10월 16~18일 · 접수 10월 7일 마감",
    url: "https://ibjjf.com/events/pan-pacific-ibjjf-jiu-jitsu-championship-2026",
  },
  {
    id: "intl-ajp-world-pro-2026",
    name: "Abu Dhabi World Professional Championship",
    date: "2026-11-19",
    location: "Abu Dhabi, UAE",
    organization: "AJP",
    ruleSet: "gi",
    type: "major",
    notes: "국제 메이저 · 11월 19~21일",
    url: "https://ajptour.com/en/event/1532",
  },
  {
    id: "intl-ibjjf-japan-national-2026",
    name: "Japanese National IBJJF Championship",
    date: "2026-12-03",
    location: "Nagoya, Japan",
    organization: "IBJJF",
    ruleSet: "both",
    type: "major",
    notes: "국제 · 12월 3~4일 · 접수 11월 25일 마감",
    url: "https://ibjjf.com/events/japanese-national-ibjjf-jiu-jitsu-championship-2026",
  },
  {
    id: "intl-ibjjf-world-nogi-2026",
    name: "World IBJJF Jiu-Jitsu No-Gi Championship",
    date: "2026-12-10",
    location: "Las Vegas, USA",
    organization: "IBJJF",
    ruleSet: "nogi",
    type: "major",
    notes: "국제 메이저 · 12월 10~12일 · 접수 11월 29일 마감",
    url: "https://ibjjf.com/events/world-ibjjf-jiu-jitsu-no-gi-championship-2026",
  },
]
