import type { FollowedEvent } from "@/lib/types/sensei"

// 2026-08-17 기준 주최 측·공식 등록 페이지로 확인한 국내 일정.
export const KOREAN_FOLLOWED_EVENTS: FollowedEvent[] = [
  { id: "kr-fantasia-cos-2026",
    name: "FANTASIA X COS", date: "2026-08-22", location: "부천체육관, 부천",
    organization: "FANTASIA × COS",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 일반 접수 8월 14일 마감",
    url: "https://www.flowcomp.co.kr/championship/67",
  },
  { id: "kr-suncheon-mayor-2026",
    name: "제1회 순천시장기 전국주짓수대회", date: "2026-08-22", location: "팔마체육관, 순천",
    organization: "순천시주짓수협회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 마감",
    url: "https://www.flowcomp.co.kr/championship/68",
  },
  { id: "kr-sunmoon-president-2026",
    name: "제4회 선문대학교총장배 주짓수 챔피언십", date: "2026-08-22",
    location: "선문대학교 스포츠과학관, 아산",
    organization: "선문대학교",
    ruleSet: "both",
    type: "major",
    notes: "국내 · Gi & No-Gi",
    url: "https://www.flowcomp.co.kr/championship/31",
  },
  { id: "kr-gangwon-club-2026",
    name: "강원특별자치도 전국 동호인 주짓수대회", date: "2026-08-22",
    location: "양양실내체육관, 양양",
    organization: "강원특별자치도주짓수회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 마감",
    url: "https://www.flowcomp.co.kr/championship/56",
  },
  { id: "kr-dobong-cup-2026",
    name: "제8회 도봉구청장배·협회장배 주짓수 챔피언십", date: "2026-08-29",
    location: "창동문화체육센터, 서울",
    organization: "도봉구주짓수회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 8월 21일 마감",
    url: "https://www.flowcomp.co.kr/championship/52",
  },
  { id: "kr-yfc-yeongam-2026",
    name: "YFC 영암 월출산배 전국 주짓수 대회", date: "2026-09-05",
    location: "영암실내체육관, 영암",
    organization: "영암군주짓수회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 8월 31일 마감",
    url: "https://spotlite.co.kr/jiujitsu/435/",
  },
  { id: "kr-vital-cup-seoul-2026",
    name: "2026 VITAL CUP GI & NO-GI SEOUL", date: "2026-09-05",
    location: "SETEC 제2전시실, 서울",
    organization: "VITAL CUP",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 접수 8월 28일 마감",
    url: "https://www.flowcomp.co.kr/championship/61",
  },
  { id: "kr-shinansan-president-2026",
    name: "신안산대학교총장배 전국 주짓수 대회", date: "2026-09-05",
    location: "신안산대학교 체육관, 안산",
    organization: "신안산대학교",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 8월 28일 마감",
    url: "https://www.flowcomp.co.kr/championship/70",
  },
  { id: "kr-d-open-2026",
    name: "D오픈 주짓수 챔피언십", date: "2026-09-05", location: "충무체육관, 대전",
    organization: "대전광역시주짓수회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 8월 28일 마감",
    url: "https://www.flowcomp.co.kr/championship/72",
  },
  {
    id: "kr-songpa-mayor-2026",
    name: "제3회 송파구청장배 주짓수대회",
    date: "2026-09-06",
    location: "송파구체육문화회관, 서울",
    organization: "송파구주짓수회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 8월 30일 마감",
    url: "https://spotlite.co.kr/jiujitsu/485/",
  },
  {
    id: "kr-ajp-seoul-2026",
    name: "AJP Tour Seoul International 2026",
    date: "2026-09-06",
    location: "부천, 대한민국",
    organization: "AJP",
    ruleSet: "both",
    type: "major",
    notes: "국내 국제대회 · Gi & No-Gi",
    url: "https://ajptour.com/en/event/1433",
  },
  {
    id: "kr-kog-seoul-adult-2026",
    name: "King of Grappling Seoul Open",
    date: "2026-09-12",
    location: "명지전문대학교 예체능관, 서울",
    organization: "King of Grappling",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 고등부·성인부 · 접수 9월 9일 마감",
    url: "https://spotlite.co.kr/jiujitsu/489/",
  },
  {
    id: "kr-gangseo-cup-2026",
    name: "제2회 강서구회장배 주짓수 챔피언십",
    date: "2026-09-12",
    location: "가양레포츠센터, 서울",
    organization: "강서구주짓수회",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 접수 9월 2일 마감",
    url: "https://www.flowcomp.co.kr/championship/21",
  },
  {
    id: "kr-cos-korea-cup-2026",
    name: "THE 5th COS BJJ KOREA CUP",
    date: "2026-09-13",
    location: "홍천종합체육관, 홍천",
    organization: "COS",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 9월 6일 마감",
    url: "https://www.flowcomp.co.kr/championship/59",
  },
  {
    id: "kr-beast-cup-goyang-2026",
    name: "고양시 BEAST CUP 주짓수대회",
    date: "2026-09-20",
    location: "고양국민체육센터, 고양",
    organization: "BEAST Championship",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 접수 9월 12일 마감",
    url: "https://spotlite.co.kr/jiujitsu/417/",
  },
  {
    id: "kr-yangju-mayor-2026",
    name: "제5회 양주시장배 주짓수 챔피언십",
    date: "2026-10-03",
    location: "양주문화예술회관, 양주",
    organization: "양주시주짓수회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 9월 27일 마감",
    url: "https://www.flowcomp.co.kr/championship/53",
  },
  {
    id: "kr-prova20-hwaseong-2026",
    name: "PROVA20 화성",
    date: "2026-10-03",
    location: "화성종합경기타운 실내체육관, 화성",
    organization: "PROVA BJJ",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 접수 9월 26일 마감",
    url: "https://www.flowcomp.co.kr/championship/76",
  },
  {
    id: "kr-dajjc-rookie-2026",
    name: "제2회 DAJJC 전국 주짓수 신인왕전",
    date: "2026-10-03",
    location: "김천실내체육관, 김천",
    organization: "DAJJC",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 접수 9월 18일 마감",
    url: "https://spotlite.co.kr/jiujitsu/366/",
  },
  {
    id: "kr-dajjc-world-2026",
    name: "DAJJC WORLD CHAMPIONSHIP",
    date: "2026-10-03",
    location: "김천실내체육관, 김천",
    organization: "DAJJC",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 10월 3~4일 · 접수 9월 18일 마감",
    url: "https://spotlite.co.kr/jiujitsu/365/",
  },
  {
    id: "kr-ansan-cup-2026",
    name: "2026 안산 체육회장기 주짓수 대회",
    date: "2026-10-09",
    location: "상록수체육관, 안산",
    organization: "안산시주짓수회",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 접수 10월 4일 마감",
    url: "https://www.flowcomp.co.kr/championship/48",
  },
  {
    id: "kr-seocho-cup-2026",
    name: "제5회 서초구회장배 주짓수대회",
    date: "2026-10-10",
    location: "서초종합체육관, 서울",
    organization: "서초구주짓수회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 10월 3일 마감",
    url: "https://www.flowcomp.co.kr/championship/71",
  },
  {
    id: "kr-goyang-mayor-2026",
    name: "6TH GOYANG MAYOR CUP · AWAKE IGNITE",
    date: "2026-10-18",
    location: "고양시청 문예회관 체육관, 고양",
    organization: "AWAKE IGNITE",
    ruleSet: "both",
    type: "major",
    notes: "국내 · 접수 9월 30일 마감",
    url: "https://www.flowcomp.co.kr/championship/80",
  },
  {
    id: "kr-geoje-cup-2026",
    name: "제6회 거제시 주짓수회장기 대회",
    date: "2026-10-31",
    location: "거제시실내체육관, 거제",
    organization: "거제시주짓수회",
    ruleSet: "gi",
    type: "major",
    notes: "국내 · 접수 10월 5일 오픈 예정",
    url: "https://www.flowcomp.co.kr/championship/44",
  },
  {
    id: "kr-adcc-busan-2026",
    name: "2026 ADCC KOREA OPEN BUSAN",
    date: "2026-12-13",
    location: "BPEX, 부산",
    organization: "ADCC Korea",
    ruleSet: "nogi",
    type: "major",
    notes: "국내 국제대회 · 접수 12월 6일 마감",
    url: "https://adcombat.com/adcc-events/adcc-korea-busan-open-2026/",
  },
]
