import type { SkillConnection } from "@/lib/types/sensei"

export const SKILL_CONNECTIONS: Record<string, SkillConnection[]> = {
  Guard: [
    { from: "Closed", to: ["HG", "Open", "Spider", "Lasso"] },
    { from: "HG", to: ["DHG", "KShield", "Sit-up"] },
    { from: "DHG", to: ["SingleSweep", "Butterfly"] },
    { from: "KShield", to: ["HG", "Sit-up", "HalfButt"] },
    { from: "Sit-up", to: ["SingleSweep", "BackTake", "ArmDrag"] },
    { from: "DLR", to: ["RDLR", "Bolo", "SLX", "KGuard"] },
    { from: "RDLR", to: ["DLR", "Bolo", "KGuard"] },
    { from: "SLX", to: ["XG", "Ashi", "Saddle"] },
    { from: "XG", to: ["SLX", "HipSweep", "Butterfly"] },
    { from: "Butterfly", to: ["XG", "HipSweep", "ArmDrag", "HalfButt"] },
    { from: "Spider", to: ["Lasso", "Triangle", "Scissor"] },
    { from: "Lasso", to: ["Spider", "Bolo", "Triangle"] },
    { from: "Lapel", to: ["Worm", "RWorm", "Squid"] },
    { from: "Worm", to: ["RWorm", "Squid", "CrabRide"] },
    { from: "Octopus", to: ["CrabRide", "BackTake"] },
    { from: "Rubber", to: ["Truck"] },
    { from: "Waiter", to: ["HG", "Sit-up"] },
    { from: "KGuard", to: ["SLX", "Ashi", "Saddle"] },
    { from: "Bolo", to: ["BackTake", "DLR"] },
  ],
  Passing: [
    { from: "HQ", to: ["KCP", "Torreando", "Bullfight", "LongStep"] },
    { from: "KCP", to: ["Smash", "HalfPass", "Mount", "SideCtrl"] },
    { from: "Torreando", to: ["LongStep", "SideCtrl", "KoB"] },
    { from: "Stack", to: ["Smash", "Mount"] },
    { from: "Smash", to: ["SideCtrl", "Mount", "KoB"] },
    { from: "LongStep", to: ["SideCtrl", "BackTake"] },
    { from: "Bullfight", to: ["Torreando", "KCP"] },
    { from: "HalfPass", to: ["KCP", "Mount"] },
    { from: "LegPummel", to: ["HQ", "KCP"] },
  ],
  Control: [
    { from: "SideCtrl", to: ["Mount", "KoB", "NS", "BackTake", "Scarf"] },
    { from: "Mount", to: ["S-Mount", "BackTake", "Crucifix"] },
    { from: "S-Mount", to: ["ArmB", "Triangle"] },
    { from: "KoB", to: ["Mount", "SideCtrl", "BackTake"] },
    { from: "BackTake", to: ["BackMount"] },
    { from: "BackMount", to: ["RNC", "BowArrow"] },
    { from: "NS", to: ["NSChoke", "Kimura", "SideCtrl"] },
    { from: "Turtle", to: ["BackTake", "Crucifix"] },
    { from: "Crucifix", to: ["Kimura", "RNC"] },
  ],
  Finishing: [
    { from: "BackMount", to: ["RNC", "BowArrow"] },
    { from: "Mount", to: ["CrossChoke", "ArmB", "Ezekiel", "ArmTriangle"] },
    { from: "S-Mount", to: ["ArmB", "Triangle"] },
    { from: "SideCtrl", to: ["Kimura", "Americana", "ArmTriangle", "Baseball"] },
    { from: "Closed", to: ["Guillotine", "Triangle", "ArmB", "Omo", "CrossChoke"] },
    { from: "Spider", to: ["Triangle", "Omo"] },
    { from: "NS", to: ["NSChoke", "Kimura"] },
    { from: "Turtle", to: ["Darce", "Anaconda"] },
    { from: "HG", to: ["Darce", "Kimura"] },
    { from: "KoB", to: ["Baseball", "ArmB"] },
  ],
  Takedowns: [
    { from: "Stand", to: ["SingleLeg", "DoubleLeg", "Bodylock", "JudoThrow", "InsideTrip", "GPull", "ArmDrag", "AnklePick"] },
    { from: "ArmDrag", to: ["BackTake", "SingleLeg"] },
    { from: "WrestleUp", to: ["SingleLeg", "DoubleLeg"] },
    { from: "GPull", to: ["Closed", "DLR", "Butterfly"] },
  ],
  LegLocks: [
    { from: "SLX", to: ["Ashi", "Saddle"] },
    { from: "Ashi", to: ["SLAshi", "IHH", "SFL"] },
    { from: "SLAshi", to: ["Ashi", "KneeBar"] },
    { from: "Saddle", to: ["IHH", "OHH"] },
    { from: "OutAshi", to: ["OHH", "KneeBar"] },
    { from: "50/50", to: ["IHH", "OHH", "ToeHold", "SFL"] },
    { from: "Estima", to: ["SFL"] },
  ],
}
